name: Main Workflow
on:  
  push:
    branches:
      - develop
    paths:
      - sample-app-2
      - sample-java-app
jobs:  
  build:     
     uses: divyatrm/pipeline/.github/workflows/build.yml@main
