name: Main Workflow
on:
  push:
    branches:
      - develop                
    paths:                                               
      - sample-java-app
      - sample-app-2
  ##workflow_dispatch:
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - uses: divyatrm/pipeline/.github/workflows/build.yml@main
