name: Main Workflow
on:
  push:
    branches:
      - develop
    paths:
      - sample-app-2
      - sample-java-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: divyatrm/pipeline/.github/workflows/build.yml@main
