name: Main Workflow
on:  
  push:
    branches:
      - develop
    paths:
      - sample-app-2
      - sample-java-app
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "Workflow is running"
      - name: Build
        uses: divyatrm/pipeline/.github/workflows/build.yml@main
